import { CartContextProvider } from '@/context/CartContext'
import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import { Raleway } from 'next/font/google'
// import { Source_Sans_3 } from 'next/font/google'
import { Noto_Sans, Open_Sans } from 'next/font/google'

const mainFont = Open_Sans({ 
  subsets: ['latin'],
  display: "swap", 
  weight: ['300','400', '500', '700'],
  style: ['normal', 'italic'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={mainFont.className}>
        <CartContextProvider>
          {children}
        </CartContextProvider>
      </body>
    </html>
  )
}
