import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import { Raleway } from 'next/font/google'
import { Source_Sans_3 } from 'next/font/google'

const mainFont = Source_Sans_3({ 
  subsets: ['latin'],
  display: "swap", 
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={mainFont.className}>{children}</body>
    </html>
  )
}
